import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SlideElementsProvider } from "@/context/SlideElementsContext";
import { SlideDimensionsProvider } from "@/context/SlideDimensionsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SlideDimensionsProvider>
          <SlideElementsProvider>
            {children}
          </SlideElementsProvider>
        </SlideDimensionsProvider>
      </body>
    </html>
  );
}
